SELECT TITLE,
	RENTAL_RATE
FROM FILM
WHERE RENTAL_RATE >
		(SELECT AVG(RENTAL_RATE) AS AVERAGE_RENTAL_RATE
			FROM FILM) ;

SELECT FILM_ID,
	TITLE
FROM FILM
WHERE FILM_ID IN
		(SELECT INVENTORY.FILM_ID
			FROM RENTAL
			INNER JOIN INVENTORY ON INVENTORY.INVENTORY_ID = RENTAL.INVENTORY_ID
			WHERE RETURN_DATE BETWEEN '2005-05-29' AND '2005-05-30' )
ORDER BY FILM_ID;

SELECT FIRST_NAME,
	LAST_NAME
FROM CUSTOMER AS C
WHERE EXISTS
		(SELECT *
			FROM PAYMENT AS P
			WHERE P.CUSTOMER_ID = C.CUSTOMER_ID
				AND AMOUNT > 11);
				
SELECT FIRST_NAME,
	LAST_NAME
FROM CUSTOMER AS C
WHERE NOT EXISTS
		(SELECT *
			FROM PAYMENT AS P
			WHERE P.CUSTOMER_ID = C.CUSTOMER_ID
				AND AMOUNT > 11);